services:
    #PostgreSQL
    postgresql:
        container_name: postgresql
        image: postgres:18
        ports:
            - "5432:5432"
        volumes:
            - ../data/postgresql:/var/lib/postgresql
        restart: always
        environment:
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "nestjs@123"
            POSTGRES_DB: "nestjs"

    #Nestjs
    nestjs:
        container_name: nestjs
        ports:
          - "3000:${PORT}"
        volumes:
          - ../nestjs/src:/nestjs/src
        depends_on:
            - postgresql
        build:
            context: ../
            dockerfile: docker/admin.dockerfile
        environment:
            APP: "${APP}"