# Name
name: admin

# Networks
networks:
    default:
        name: admin

# Services
services:
    # PostgreSQL
    postgresql:
        image: postgres:18
        volumes:
            - ../data/postgresql:/var/lib/postgresql
        restart: always
        environment:
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_PASSWORD: "${DB_PASS}"
            POSTGRES_DB: "${DB_NAME}"

    # Nestjs
    nestjs:
        ports:
          - "3000:${PORT}"
        volumes:
          - ../nestjs/src:/nestjs/src
        depends_on:
            - postgresql
        build:
            context: ../
            target: ${NODE_ENV}
            dockerfile: docker/admin.dockerfile
        environment:
            APP: "${APP}"